# Generated by Django 4.1.4 on 2023-01-14 18:59

import cloudinary_storage.storage
import core.validator
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Minister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('publish', models.IntegerField(default=0)),
                ('content', models.CharField(choices=[('song', 'song'), ('message', 'message'), ('presentation', 'presentation')], default='presentation', max_length=15)),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('picture', models.ImageField(upload_to='images/author/')),
                ('times_played', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Content',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=240)),
                ('content', models.FileField(blank=True, null=True, storage=cloudinary_storage.storage.VideoMediaCloudinaryStorage, upload_to='content/audio', validators=[core.validator.validate_file_extension])),
                ('image', models.ImageField(upload_to='content/images')),
                ('description', models.TextField(blank=True, null=True)),
                ('date_created', models.DateTimeField()),
                ('times_played', models.IntegerField(default=0)),
                ('minister', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='minister', to='core.minister')),
                ('tag', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.events')),
            ],
        ),
    ]
